### ISSUE TITLE
Alt + double click does not works with offline files

### ISSUE THREAD

**Issue by laerreal** [dicthub/DictHubExtension#1]
When I open a local file (e.g. `file:///path/to/file.html`) and then
do double click on a word, holding Alt, nothing happens.
During normal web browsing (`http://...`) it works.

I noticed, another dictionary-like extensions with popup windows
have same problem.

Firefox 70.0 (64-bit), Ubuntu 18.04.

**Comment by willings** [comment]
Thank you for reporting the issue, reproduced locally, error log:
```
Unchecked runtime.lastError: Cannot access contents of url "file:///tmp/helloworld.html". Extension manifest must request permission to access this host.
```

Unfortunately it is the current expected behavior. To access `file:///`, extension needs to declare permission similar as `http://` and `https://`. Some user might have concern on broader permission.

But looks it's a pretty useful improvement, let's try to support local files in next version :-)

**Comment by laerreal** [comment]
I tried update and delete-install the extension. But problem still exists.

**Comment by laerreal** [comment]
But, it works with Alt+W. I did know about that shortcut earlier. So, I can't say is it because of new update.
